pagopa/azurerm

- kubernetes_cluster/README.md
- kubernetes_cluster/main.tf
- kubernetes_cluster/variables.tf
Unfortunately to assign the network contributor role to ask service principal to the vnet .... terraform cloud needs to be User access admininstrator.
> Ask role assignment vnet contributor

- .gitignore
- .pre-commit-config.yaml
- .tflint.hcl
- api_management/README.md
- api_management_api/README.md
- azure_devops_agent/README.md
- container_registry/README.md
- eventhub/README.md
- eventhub/main.tf
- eventhub/outputs.tf
- eventhub/variables.tf
- jumpbox/README.md
- jumpbox/main.tf
- key_vault/README.md
- key_vault/main.tf
- key_vault_secrets_query/README.md
- kubernetes_cluster/README.md
- kubernetes_cluster/main.tf
- kubernetes_cluster/variables.tf
- postgresql_server/README.md
- redis_cache/README.md
- storage_account/README.md
- subnet/README.md
- virtual_network/README.md
- Fix tfsec and pre-commit rules
- Refactor eventhub module
> Fix tfsec and refactor eventhub

- eventhub/outputs.tf
Fix:
│ Error: Duplicate object key
> Fix output keys of eventhub module

- eventhub/README.md
- eventhub/main.tf
- eventhub/variables.tf
https://docs.microsoft.com/en-us/azure/event-hubs/private-link-service
> Add eventhub private endpoint

- kubernetes_cluster/README.md
- kubernetes_cluster/main.tf
- kubernetes_cluster/variables.tf
- https://docs.microsoft.com/en-gb/azure/azure-monitor/containers/container-insights-update-metrics
- Allow to use Azure AD for `az aks get-credentials` https://docs.microsoft.com/it-it/azure/aks/concepts-identity
> Add Monitoring Metrics Publisher and AAD Fix

- function_app/README.md
- function_app/main.tf
- function_app/outputs.tf
- function_app/variables.tf
Add function_app module configuration
> [#IP-431] add function_app module

- app_gateway/README.md
- app_gateway/main.tf
- app_gateway/variables.tf
add firewall policy for listener
add pick_host_name_from_backend, request_timeout and fqdns for backend
> add firewall policy and backend vars for app gateway

- cdn/main.tf
- cdn/variables.tf
Allowing multiple rule conditions
> Allowing multiple rule conditions

- .gitignore
- cdn/main.tf
- cdn/variables.tf
The purpose of this PR is to : 
- create APEX `azurerm_dns_a_record` iff the DNS zone name equal to HOST NAME
- added `azurerm_dns_cname_record` set to custom subdomain
> [PCFG-56] fix CDN module

- cdn/outputs.tf
CDN will output inner storage info
> exporting storage infos

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/release.yml
- .pre-commit-config.yaml
- .tflint.hcl
- README.md
- add automatic release when merge pr
- add readme
- add pr template
- remove tflint
> Add automatic release on merge pr

- key_vault/main.tf
fix key vault monitoring that cause unwanted changes on plans
fix changes on plans
> fix key vault diagnostic_setting unwanted changes

- .gitignore
- kubernetes_cluster/variables.tf
force vm size in AKS
avoid default parameter, because we will have an old vms in the future
> INFRA-335-azurerm-aks-remove-default-sku

- postgresql_server/README.md
- postgresql_server/main.tf
- postgresql_server/outputs.tf
- postgresql_server/variables.tf
- support bacic SKUs for dev envs
- optional private endpoint
- removed private dns zone and virtual network links
- optional allowed subnets
- add tfsec suggestions
cost savings, support for multiple postgreql
this PR contains a breaking change.
> Postgreql refactor

- api_management_api/README.md
- azure_devops_agent/README.md
- cdn/main.tf
- cdn/variables.tf
- container_registry/README.md
- jumpbox/README.md
- kubernetes_cluster/main.tf
- load_balancer/main.tf
- nat_gateway/main.tf
- redis_cache/README.md
- storage_account/README.md
- subnet/README.md
- virtual_network/README.md
format and docs, no code change
> format docs

- azure_devops_agent/script-config.json
- azure_devops_agent/script-config.sh
installing pip modules on azure devops agent
> Install python pip modules on azure devops agent

- README.md
- key_vault/main.tf
- key_vault/variables.tf
change kv retention policy days
key vault need a 90 days of retention to use some function
> fix soft_delete_retention_days

- cosmosdb/README.md
- cosmosdb/main.tf
- cosmosdb/output.tf
- cosmosdb/variables.tf
> Add cosmosdb module

- key_vault_secrets_query/main.tf
add required provider
warning when use provider to change subscription
> Add provider azurerm for key vault query

- storage_object_replication/README.md
- storage_object_replication/main.tf
- storage_object_replication/variables.tf
> Module storage object replication

- vpn_gateway/main.tf
- vpn_gateway/outputs.tf
- vpn_gateway/variables.tf
- add external ip
- remove logs from internal workspace
> VPN gw add external ip, remove internal logs

- dns_forwarder/Corefile
- dns_forwarder/README.md
- dns_forwarder/main.tf
- dns_forwarder/vars.tf
> add-dns-forwarder

- app_gateway/main.tf
add `affinity_cookie_name = "ApplicationGatewayAffinity"`
The value is added when we manual changes something in azure portal.
This fix help to avoid unwanted changes in terraform plans.
https://dev.azure.com/pagopaspa/io-iac-projects/_build/results?buildId=12962&view=logs&j=16499c94-c803-5abe-9884-831ee5cb9286&t=89fae0c5-bedb-5ea2-19fd-64d84097a413&l=475
> app_gateway fix affinity_cookie_name

- kubernetes_cluster/main.tf
- kubernetes_cluster/variables.tf
> enable aks audit logs

- redis_cache/README.md
- redis_cache/main.tf
- redis_cache/variables.tf
add private endpoint for redis
we can use standard plan with private redis access
> redis add private endpoint

- api_management_api/main.tf
- api_management_api/variables.tf
The purpose of this PR is to manage for [api_management_api](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api) resources , `oauth2_authorization` block too.
> [PCFG-98] Added oauth2_authorization field

- app_service/README.md
- app_service/main.tf
- app_service/outputs.tf
- app_service/variables.tf
add plan type: internal or external
use shared app service plans
> App service add external plan

- kubernetes_cluster/variables.tf
Improved aks vm size description
Help the people to understand with size is better
> updated info about vm size

- application_insights_web_test_preview/README.md
- application_insights_web_test_preview/main.tf
- application_insights_web_test_preview/template.tftpl
- application_insights_web_test_preview/variables.tf
> Application insight web test module

- cdn/outputs.tf
> fix-cdn-fqdn-outputs

- cosmosdb/README.md
- cosmosdb/main.tf
- cosmosdb/variables.tf
add zone_redundant option 
resiliency for prod envs
> Add zone_redundant option to comosdb

- jwt-keys/README.md
- jwt-keys/main.tf
- jwt-keys/outputs.tf
- jwt-keys/variables.tf
> Add jwt keys

- app_service/README.md
- app_service/main.tf
- app_service/variables.tf
> App service vnet route all enable

- api_management_api/main.tf
- api_management_api/variables.tf
This PR proposes to add the input variable `revision_description` to module `api_management_api`
- Add the input variable `revision_description` to module `api_management_api`
In my case this change is required to align changes made via Azure portal to Terraform code. In detail, I had to create and make current a different revision of the api policy award_period
> [CEN-1235] Add revision_description input in module api_management_api

- app_service_slot/README.md
- app_service_slot/main.tf
- app_service_slot/outputs.tf
- app_service_slot/variables.tf
> [#INFRA-475] Add appservice slot module

- app_service/README.md
- app_service/main.tf
- app_service/variables.tf
remove optional capacity from app service module 
unwanted changes when use autoscaling
> Remove capacity from app service module

- app_service_slot/README.md
- app_service_slot/main.tf
- app_service_slot/variables.tf
- add vnet_route_all_enabled to app_service_slot
fix missing param
> Add vnet_route_all_enabled to app_service_slot

- api_management_api/main.tf
- api_management_api/variables.tf
- app_service/README.md
- app_service/main.tf
- app_service/variables.tf
- app_service_slot/README.md
- app_service_slot/main.tf
- app_service_slot/outputs.tf
- app_service_slot/variables.tf
- azure_devops_agent/script-config.sh
- function_app/README.md
- function_app/main.tf
- function_app/outputs.tf
- function_app/variables.tf
- function_app_slot/README.md
- function_app_slot/main.tf
- function_app_slot/outputs.tf
- function_app_slot/variables.tf
- storage_management_policy/README.md
- storage_management_policy/main.tf
- storage_management_policy/outputs.tf
- storage_management_policy/variables.tf
- storage_object_replication/main.tf
- storage_object_replication/variables.tf
It's still a work in progress.
* Module for the function app slot.
* I had to introduce few optional variable to support existing names not aligned with our new naming convention.
* A new major **rel v2.1.0** it is needed.
> Module function app slot

- function_app/main.tf
* fix name generation for `function_app`'s internal storage account
In https://github.com/pagopa/azurerm/pull/151 we accidentally introduced a bug in `function_app` module: the (optional) storage account for supporting durable functions has a wrong formatting for name.
> fix durable storage name

- function_app_slot/main.tf
> Fix function app slot

- function_app/outputs.tf
> Fix function app output

- .github/workflows/static_analysis.yml
> Fix ci names

- .github/workflows/static_analysis.yml
- README.md
> Add status badge

- cdn/main.tf
- cdn/variables.tf
generic delivery_rule block dynamic
To allow the configuration of a complete delivery_rule
> cdn delivery_rule configuration

- cosmosdb_sql_database/README.md
- cosmosdb_sql_database/main.tf
- cosmosdb_sql_database/outputs.tf
- cosmosdb_sql_database/variables.tf
> Module cosmosdb sql database

- cosmosdb_sql_container/README.md
- cosmosdb_sql_container/main.tf
- cosmosdb_sql_container/outputs.tf
- cosmosdb_sql_container/variables.tf
> Module cosmosdb sql container

- function_app_slot/main.tf
> Fix fn-slot settings

- .utils/provider.tf
- api_management/main.tf
- api_management/outputs.tf
- api_management_api/main.tf
- api_management_api/outputs.tf
- terraform_run_all.sh
- add outputs to apim modules
- add for terraform validate apim requires provider features but adding it into module break some projects. So we changed github action to temp add required provider features into modules
> Add apim outputs

- cosmosdb_account/README.md
- cosmosdb_account/main.tf
- cosmosdb_account/variables.tf
> Fix cosmosdb sql endpoint 

- cosmosdb_account/main.tf
> Fix cosmos private service connection name

- app_service/README.md
- app_service/main.tf
- app_service/variables.tf
- app_service_slot/README.md
- app_service_slot/main.tf
- app_service_slot/variables.tf
> Fix app service vnet integration count

- app_gateway/main.tf
- app_gateway/variables.tf
app gateway will accept URL rewrite + fixed rule condition values
> App gateway url rewrite

- azure_devops_agent/script-config.sh
add docker to devops agent pool
some devops task need docker
> add docker and zip to devops agent

- subnet/README.md
- subnet/variables.tf
- Readme added examples 
- Variables:  better descriptions and comments
Improve documentation
> subnet-improve-docs

- azure_devops_agent/devops_agent.json
- azure_devops_agent/repair_devops_agent.sh
Add repair script for azure devops agent script
Old azure devops agents ref to tagged script-config.sh, so we need to migrate all agents to point to main branch config.
This script helps to change ref without recreate devops agents in Azure DevOps
> add repair script for azure devops agent

- azure_devops_agent/script-config.sh
add helm and kubectl to devops agents
tools required for k8s deploy
> add helm kubectl to devops agent

- function_app/main.tf
- function_app/variables.tf
- function_app_slot/main.tf
- function_app_slot/variables.tf
> Add use_32_bit_worker_process for fnapp and fnapp_slot

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .releaserc.json
- README.md
- function_app_slot/main.tf
- add semantic versioning workflow
- add pr title and commit checks
- refactor release workflow
follow versioning best practices.
All actions not requires admin permissions to commit on protected branches (action will fails if it'll try to commit on protected branches)
> feat: Add semantic versioning

- function_app/main.tf
- function_app_slot/main.tf
> fix(function): Remove 3party auth

- kubernetes_cluster/README.md
- kubernetes_cluster/main.tf
- kubernetes_cluster/variables.tf
> fix: K8s addons

- kubernetes_cluster/README.md
- kubernetes_cluster/main.tf
> feat: Enable KeyVault secret autorotation

- kubernetes_ingress/README.md
- kubernetes_ingress/assets/mounter.yaml.tpl
- kubernetes_ingress/assets/tls.yaml.tpl
- kubernetes_ingress/main.tf
- kubernetes_ingress/variables.tf
- kubernetes_pod_identity/README.md
- kubernetes_pod_identity/main.tf
- kubernetes_pod_identity/variables.tf
> feat: Kubernetes ingress and pod identity

- azure_devops_agent/README.md
- azure_devops_agent/versions.tf
- cdn/README.md
- cdn/versions.tf
- kubernetes_cluster/README.md
- kubernetes_cluster/versions.tf
- kubernetes_ingress/README.md
- kubernetes_ingress/versions.tf
- kubernetes_pod_identity/README.md
- kubernetes_pod_identity/versions.tf
- postgres_flexible_server/README.md
- postgres_flexible_server/versions.tf
null provider >= 3.0.0
a previous constraint, don't allow the build for some projects
> fix: Change constraint to null >= 3.0.0

- application_insights_web_test_preview/README.md
- application_insights_web_test_preview/variables.tf
> fix(application_insights_web_test_preview): Fix default value for content_validation

- app_service_slot/main.tf
add php_version, python_version, http2_enabled
same as prod slot
```sh
```
> fix: Add missing configs to app_service_slot

- .pre-commit-config.yaml
- jumpbox/README.md
- jwt_keys/README.md
- kubernetes_ingress/README.md
- kubernetes_ingress/main.tf
- kubernetes_pod_identity/README.md
- kubernetes_pod_identity/outputs.tf
> feat: Add identity as output to kubernetes_pod_identity

- kubernetes_ingress/README.md
- kubernetes_ingress/main.tf
- kubernetes_pod_identity/main.tf
> feat: Attach KV policy to pod identity only if needed

- kubernetes_ingress/README.md
- kubernetes_ingress/main.tf
It will use `networking/v1` instead of deprecated `extensions/v1beta1`.
```sh
```
> fix: Update K8s ingress api

- kubernetes_pod_identity/README.md
- kubernetes_pod_identity/main.tf
- kubernetes_pod_identity/variables.tf
> fix: Ignore key_vault and tenant_id in pod identity when not needed

- kubernetes_cluster/01_main.tf
Add aks maintenance_window
```sh
```
> fix: Add aks maintenance_window

- letsencrypt_credential/README.md
- letsencrypt_credential/main.tf
- letsencrypt_credential/variables.tf
- letsencrypt_credential/versions.tf
Add let's encrypt credential
```sh
```
> feat(le_credential): Add let's encrypt credential

- kubernetes_ingress/README.md
- kubernetes_ingress/main.tf
- kubernetes_ingress/variables.tf
> fix: Add option to disable https redirect

- kubernetes_cluster/01_main.tf
> feat: Deprecate addon_profile from kubernetes_cluster

- cosmosdb_sql_container/main.tf
- vpn_gateway/README.md
> fix: Ignore changes to autoscale for cosmosdb containers

- data_factory/main.tf
- vpn_gateway/README.md
This PR proposes to add a System Managed Identity for Azure Data Factory.
- set a System Assigned Managed Identity for Azure data Factory
This PR solves the problem of creating Linked Service for Azure Data Factory avoiding the use of the access keys
The pre-commit checks proposes many alterations to READMEs, I don't know if I can commit ad push them
```sh
```
> fix: Set System Managed Identity for Data Factory

- .pre-commit-config.yaml
- cdn/README.md
- cdn/main.tf
- vpn_gateway/README.md
This PR proposes to add an A record when hostname and dns_zone satisfy the following constraint 
hostname = subdomain.dns_zone
- New A record
This PR solves the problem of creating an A record when hostname = subdomain.dns_zone
```sh
```
> fix: Generate A record for CDN [IID-10] 

- eventhub/main.tf
Fixed null value handling in ternary operation: with my terraform version (1.1.7) I'm obtaining the following error:
`The condition value is null. Conditions must either be true or false.`
```sh
```
> fix: Fixed null value handling in ternary operation

- azure_devops_agent/script-config.sh
> feat: Add k6 load test params for devops agent

- jumpbox/README.md
- jumpbox/versions.tf
- jwt_keys/README.md
- jwt_keys/versions.tf
> fix: Set tls version

- letsencrypt_credential/README.md
- letsencrypt_credential/main.tf
- letsencrypt_credential/variables.tf
> fix: Add certbot sha256

- azure_devops_agent/script-config.sh
- add yq to azure devops agent
We use yq in helm release pipelines
```sh
```
> fix: Add yq to azure devops agent

- application_insights_web_test_preview/README.md
- application_insights_web_test_preview/main.tf
- application_insights_web_test_preview/variables.tf
- tls_checker/README.md
- tls_checker/versions.tf
> fix: App insights id

- app_service/README.md
- app_service/main.tf
- app_service/variables.tf
- app_service_slot/README.md
- app_service_slot/main.tf
- app_service_slot/variables.tf
> feat(app_service): Add optional https_only var

- app_service/README.md
- app_service/main.tf
- app_service/variables.tf
- app_service_slot/README.md
- app_service_slot/main.tf
- app_service_slot/variables.tf
> feat(app_service): Add client_affinity_enabled variable

- azure_devops_agent/README.md
- azure_devops_agent/versions.tf
- cdn/README.md
- cdn/versions.tf
- kubernetes_cluster/99_versions.tf
- kubernetes_cluster/README.md
- kubernetes_pod_identity/README.md
- kubernetes_pod_identity/versions.tf
- letsencrypt_credential/README.md
- letsencrypt_credential/versions.tf
- postgres_flexible_server/05_versions.tf
- postgres_flexible_server/README.md
- tls_checker/README.md
- tls_checker/main.tf
- tls_checker/variables.tf
- tls_checker/versions.tf
> fix(tls_checker): Fix generic action group list

- tls_checker/README.md
- tls_checker/versions.tf
> fix(tls_checker): Update versions.tf

- azure_devops_agent/script-config.sh
> feat: Add jq installation

- function_app/README.md
- function_app/main.tf
- storage_management_policy/main.tf
> fix(function_app): Fix create blob container management policy tolist

- app_service/main.tf
- app_service_slot/main.tf
- function_app/main.tf
- function_app_slot/main.tf
> fix: Override vnet restrictions name in app service and function app

- app_service/main.tf
- app_service_slot/main.tf
- function_app/main.tf
- function_app_slot/main.tf
> fix: Override vnet restrictions name in app service and function app, add name

- elastic_stack/main.tf
- elastic_stack/variables.tf
- elastic_stack/versions.tf
- elastic_stack/yaml/SecretProvider.yaml
- elastic_stack/yaml/apm.yaml
- elastic_stack/yaml/crds.yaml
- elastic_stack/yaml/elastic.yaml
- elastic_stack/yaml/ingress.yaml
- elastic_stack/yaml/kibana.yaml
- elastic_stack/yaml/operator.yaml
Add elastic_stack module
```sh
```
> feat: Add elastic stack module

- jwt_keys/README.md
- jwt_keys/main.tf
- jwt_keys/variables.tf
- jwt_keys/versions.tf
- upgrade to 4.0.4 provider
- add early_renewal_hours default to 720 (30 days)
```sh
```
> feat: Upgrade JWT keys module

- elastic_stack/main.tf
- elastic_stack/variables.tf
- elastic_stack/yaml/SecretProvider.yaml
- elastic_stack/yaml/elastic.yaml
- elastic_stack/yaml/ingress.yaml
module storage fixing anche elastic namespace
```sh
```
> feat: Fix storage and namespace

- kubernetes_cluster/10_outputs.tf
- kubernetes_cluster/README.md
> fix: AKS kube_config outputs not supported in 1.24

- key_vault/README.md
- key_vault/main.tf
- key_vault/variables.tf
from https://github.com/pagopa/terraform-azurerm-v3/pull/39
```sh
```
> feat: Add Key vault rbac

- cosmosdb_account/main.tf
> fix(comsos_db): Private endpoint with capabilities

- elastic_stack/README.md
- elastic_stack/main.tf
- elastic_stack/variables.tf
> feat: Remove unused variable

- elastic_stack/main.tf
- elastic_stack/yaml/agent.yaml
> feat: Change namespace to elastic-agent

- elastic_stack/README.md
- elastic_stack/main.tf
- elastic_stack/variables.tf
- elastic_stack/yaml/SecretProvider.yaml
- elastic_stack/yaml/agent.yaml
- elastic_stack/yaml/apm.yaml
- elastic_stack/yaml/elastic.yaml
- elastic_stack/yaml/ingress.yaml
- elastic_stack/yaml/kibana.yaml
- elastic_stack/yaml/mounter.yaml
> feat: Fix elastic namespace

- elastic_stack/yaml/agent.yaml
- elastic_stack/yaml/apm.yaml
- elastic_stack/yaml/elastic.yaml
- elastic_stack/yaml/kibana.yaml
- elastic_stack/yaml/mounter.yaml
- elastic_stack/yaml/operator.yaml
> feat: Fine tuning elk

- elastic_stack/README.md
- elastic_stack/main.tf
- elastic_stack/yaml/elastic.yaml
- elastic_stack/yaml/ingress_elastic.yaml
- elastic_stack/yaml/ingress_logstash.yaml
- elastic_stack/yaml/logstash.yaml
- elastic_stack/yaml/logstash_config.yaml
> feat: Test elastic

- virtual_network_peering/main.tf
> fix: Fix vnet peering name

- elastic_stack/README.md
- elastic_stack/logs-generic/component_logs-generic-mappings.json
- elastic_stack/logs-generic/component_logs-generic-settings.json
- elastic_stack/logs-generic/data_view.json
- elastic_stack/logs-generic/ilm_policy_logs-generic.json
- elastic_stack/logs-generic/index_template_logs-generic.json
- elastic_stack/main.tf
- elastic_stack/variables.tf
- elastic_stack/yaml/ingress_logstash.yaml
- elastic_stack/yaml/logstash_config.yaml
> feat: Test logstash

- elastic_stack/README.md
- elastic_stack/main.tf
- elastic_stack/variables.tf
> feat: Add elasticsearch license

- azure_devops_agent/script-config.sh
> fix: Update script-config.sh with Python3 installation

- elastic_stack/README.md
- elastic_stack/main.tf
- elastic_stack/variables.tf
- elastic_stack/yaml/elastic.yaml
> feat: Add azure repo config

- azure_devops_agent/README.md
- azure_devops_agent/main.tf
- azure_devops_agent/variables.tf
> feat: Azdo zones
